import numpy as np

LUNAR_RADIUS = 1737400
EARTH_X = 361000 * 1000
EARTH_Y = 0 * 1000
EARTH_Z = -42100 * 1000

LUNAR_RADIUS_METERS = (LUNAR_RADIUS )
EARTH_X_METERS = (EARTH_Y)
EARTH_Y_METERS = (EARTH_X)
EARTH_Z_METERS = (EARTH_Z)

R = np.sqrt(EARTH_X_METERS ** 2 + EARTH_Y_METERS ** 2 + EARTH_Z_METERS ** 2)

EARTH_LAT = np.arcsin(EARTH_Z_METERS / R)
EARTH_LONG = np.arctan2(EARTH_Y_METERS, EARTH_X_METERS)

print(EARTH_LAT)
print(EARTH_LONG)
